Repository CruzHacks/cruzhacks-2021-website, pull requests merged in 2020-12, with the labels that each got.

#90 [Deploy] November 30
  src/components/Button/index.view.tsx
  src/stylesheets/_variables.scss
  src/views/Home/Home.scss
  src/views/Home/index.view.tsx
Labels: deploy

#91 Milestones component.
  src/components/Background/Background.scss
  src/images/components/milestones/background.svg
  src/images/components/milestones/pencil.svg
  src/images/components/milestones/shell.svg
  src/stylesheets/_typography.scss
  src/stylesheets/_variables.scss
  src/views/Home/components/Milestones/index.view.tsx
  src/views/Home/components/Milestones/milestones.scss
  src/views/Home/index.view.tsx
Labels: enhancement, work in progress

#94 Mission section
  src/components/Background/Background.scss
  src/images/components/mission/background.svg
  src/images/components/mission/can-left.svg
  src/images/components/mission/can-right.svg
  src/images/components/mission/flower.svg
  src/stylesheets/_typography.scss
  src/stylesheets/_variables.scss
  src/views/Home/components/Milestones/milestones.scss
  src/views/Home/components/Mission/index.view.tsx
  src/views/Home/components/Mission/mission.scss
  src/views/Home/index.view.tsx
Labels: enhancement, work in progress

#130 footer component
  src/views/Home/components/Footer/footer.scss
  src/views/Home/components/Footer/index.view.tsx
  src/views/Home/index.view.tsx
Labels: enhancement
