Repository CruzHacks/cruzhacks-2021-website, pull requests merged in 2021-01, with the labels that each got.

#97 Prizes component.
  .stylelintrc.js
  src/components/Background/Background.scss
  src/images/components/prizes/background.svg
  src/images/components/prizes/best_beginner.svg
  src/images/components/prizes/best_ui_ux.svg
  src/images/components/prizes/earth_hacks.svg
  src/images/components/prizes/health_hacks.svg
  src/images/components/prizes/justice_hacks.svg
  src/images/components/prizes/sc_hacks.svg
  src/images/sponsors/pinnacle.svg
  src/stylesheets/_typography.scss
  src/views/Home/components/FAQ/faq.scss
  src/views/Home/components/FAQ/index.view.tsx
  src/views/Home/components/Prizes/index.view.tsx
  src/views/Home/components/Prizes/prizes.scss
  src/views/Home/components/Sponsors/sponsors.scss
  src/views/Home/index.view.tsx
  src/views/Home/props/faq.json
  src/views/Home/props/mission.json
  src/views/Home/props/prizes.js
Labels: enhancement, work in progress

#95 navigation bar
  .eslintrc.js
  package.json
  src/components/Background/Background.scss
  src/components/Button/Button.scss
  src/components/Button/index.view.tsx
  src/components/MLHBanner/mlhbanner.scss
  src/components/Navbar/Navbar.scss
  src/components/Navbar/index.view.tsx
  src/stylesheets/_typography.scss
  src/stylesheets/_variables.scss
  src/views/Home/Home.scss
  src/views/Home/components/Hero/Hero.scss
  src/views/Home/components/Hero/index.view.tsx
  src/views/Home/index.view.tsx
  src/views/Home/props/hero.json
  src/views/Home/props/navbar.js
  yarn.lock
Labels: enhancement

#141 Feature/error
  src/images/error/404.svg
  src/images/error/lens-flare__bottom.svg
  src/images/error/lens-flare__left.svg
  src/images/error/lens-flare__top.svg
  src/routes/routes.tsx
  src/stylesheets/_typography.scss
  src/stylesheets/_variables.scss
  src/views/Error/Error.scss
  src/views/Error/Error.test.js
  src/views/Error/index.view.tsx
Labels: enhancement

#159 Footer - 2nd Iteration
  src/components/EmailSubscription/EmailSubscription.scss
  src/images/arrow.svg
  src/images/components/footer/2020.svg
  src/images/components/footer/facebook.svg
  src/images/components/footer/instagram.svg
  src/images/components/footer/linkedIn.svg
  src/images/components/footer/twitter.svg
  src/stylesheets/_variables.scss
  src/views/Home/components/Footer/footer.scss
  src/views/Home/components/Footer/index.view.tsx
  src/views/Home/index.view.tsx
  src/views/Home/props/footer.tsx
  src/views/Team/components/Footer/Footer.scss
Labels: enhancement

#173 Feature/footer
  src/components/Navbar/Navbar.scss
  src/components/Navbar/index.view.tsx
  src/views/Error/Error.scss
  src/views/Error/index.view.tsx
  src/views/Home/components/Footer/footer.scss
  src/views/Home/components/Footer/index.view.tsx
  src/views/Home/props/footer.js
Labels: bug

#177 updated schedule
  src/views/Home/components/Schedule/index.view.tsx
Labels: enhancement

#179 [Deploy] January 15
  src/views/Home/components/Schedule/index.view.tsx
Labels: deploy

#181 [Deploy] January 16
  src/components/Background/Background.scss
  src/stylesheets/_typography.scss
  src/views/Home/components/Hero/Hero.scss
  src/views/Home/components/Schedule/index.view.tsx
  src/views/Home/components/Schedule/schedule.scss
Labels: deploy
